// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bookmark struct {
	ID        int64
	Userid    int64
	Postid    int64
	Isenabled bool
}

type Chat struct {
	ID         int64
	Name       string
	Members    []int64
	Coverimage pgtype.Text
}

type Follow struct {
	ID         int64
	Followerid int64
	Followedid int64
	Isenabled  bool
}

type Like struct {
	ID        int64
	Userid    int64
	Postid    int64
	Isenabled bool
}

type Message struct {
	ID          int64
	Senderid    int64
	Chatid      int64
	Content     pgtype.Text
	Attachments []string
}

type Post struct {
	ID          int64
	Authorid    int64
	Content     pgtype.Text
	Replyto     pgtype.Int8
	Threadstart pgtype.Int8
	Quoteof     pgtype.Int8
	Attachments []string
}

type PostsExtra struct {
	ID                int64
	Authorid          int64
	Username          string
	Displayname       pgtype.Text
	Bio               pgtype.Text
	Avatar            pgtype.Text
	Banner            pgtype.Text
	Isfollowerspublic bool
	Isfollowingpublic bool
	Ispostspublic     bool
	Islikespublic     bool
	Countlikes        int64
	Countposts        int64
	Countisfollowing  int64
	Countfollowedby   int64
	Content           pgtype.Text
	Replyto           pgtype.Int8
	Quoteof           pgtype.Int8
	Attachments       []string
	Postcountlikes    int64
	Postcountquotes   int64
	Postcountreplies  int64
	Threadstart       pgtype.Int8
}

type Token struct {
	ID     int64
	Userid int64
	Token  string
	Device string
}

type User struct {
	ID                int64
	Username          string
	Password          string
	Email             string
	Salt              string
	Isvalidated       bool
	Isbanned          bool
	Displayname       pgtype.Text
	Bio               pgtype.Text
	Avatar            pgtype.Text
	Banner            pgtype.Text
	Prefferedlanguage string
	Isfollowingpublic bool
	Isfollowerspublic bool
	Ispostspublic     bool
	Islikespublic     bool
}

type Usersdetail struct {
	ID                int64
	Username          string
	Displayname       pgtype.Text
	Bio               pgtype.Text
	Avatar            pgtype.Text
	Banner            pgtype.Text
	Isfollowerspublic bool
	Isfollowingpublic bool
	Ispostspublic     bool
	Islikespublic     bool
	Countlikes        int64
	Countposts        int64
	Countisfollowing  int64
	Countfollowedby   int64
	Prefferedlanguage string
}

type Verification struct {
	ID         int64
	Userid     int64
	Code       string
	Validuntil pgtype.Timestamp
}
