// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package queries

import (
	"context"
)

const getLoggedInUserProfile = `-- name: GetLoggedInUserProfile :one
SELECT usersDetails.id,
	usersDetails.username,
	usersDetails.displayname,
	usersDetails.bio,
	usersDetails.avatar,
	usersDetails.banner,
	usersDetails.isfollowerspublic,
	usersDetails.isfollowingpublic,
	usersDetails.ispostspublic,
	usersDetails.islikespublic,
	usersDetails.countlikes,
	usersDetails.countposts,
	usersDetails.countisfollowing,
	usersDetails.countfollowedby,
	usersDetails.prefferedLanguage
FROM usersDetails
	JOIN tokens ON tokens.userid = usersDetails.id
WHERE tokens.token = $1
`

func (q *Queries) GetLoggedInUserProfile(ctx context.Context, token string) (Usersdetail, error) {
	row := q.db.QueryRow(ctx, getLoggedInUserProfile, token)
	var i Usersdetail
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Displayname,
		&i.Bio,
		&i.Avatar,
		&i.Banner,
		&i.Isfollowerspublic,
		&i.Isfollowingpublic,
		&i.Ispostspublic,
		&i.Islikespublic,
		&i.Countlikes,
		&i.Countposts,
		&i.Countisfollowing,
		&i.Countfollowedby,
		&i.Prefferedlanguage,
	)
	return i, err
}
