@apiURL = http://localhost:8080

###REMEMBER TO NOT PUT TRAILING COMMAS IN JSON REQUESTS
GET {{apiURL}}/examples HTTP/2.0
# curl -X POST -H "Content-Type: application/json" --data "{\"username\":\"john\",\"password\":\"doe\", \"email\":\"email\"}" localhost:8080/register
###FAILED REGISTER
POST {{apiURL}}/register
Content-Type: "application/json"

{
	"username": "test",
	"password": "TestTest123",
	"email": "email"
}



###SUCCESSFUL REGISTER
POST {{apiURL}}/register
Content-Type: "application/json"

{
	"username": "Gami",
	"password": "Haslo123",
	"email": "gamiofficial0@gmail.com"
}

###FAILED LOGIN
POST {{apiURL}}/login
Content-Type: "application/json"

{
	"email": "test@test.com",
	"password": "TestTest13",
	"deviceName": "testDevice"
}

###SUCCESSFUL LOGIN
POST {{apiURL}}/login
Content-Type: "application/json"

{
	"email": "gamiofficial0@gmail.com",
	"password": "Haslo123",
	"deviceName": "testDevice"
}


###FAILED LOGOUT

POST {{apiURL}}/log-out
Authorization: yesss


@token = 139637715829260297.6TUQtmpewtmdQyZ5MFdEBEi81jtn0VHRWbK68VxLlnUVBAEOC19mh5cnMp_3CQ_vLxnzP9CCRlJiTj3CS-QxexdEtMDTOO2nQpUu3MvR3TFSAedmC7b808w2QVaDBpOE3TDleXqmUo0E_WBkVHko1VZrUZZ7VLgiO7ey_vSViJ4

###setDisplayName test
POST {{apiURL}}/setDisplayName
Authorization: {{token}}
Content-Type: "application/json"

{
	"displayName": "Gami The Creator"
}

###setBio test
POST {{apiURL}}/setBio
Authorization: {{token}}
Content-Type: "application/json"

{
	"bio": "Im just a silly little dude :3"
}

###ToggleIsFollowersPublic test
POST {{apiURL}}/toggleIsFollowersPublic
Authorization: {{token}}

###ToggleIsFollowingPublic test
POST {{apiURL}}/toggleIsFollowingPublic
Authorization: {{token}}

###ToggleIsPostsPublic test
POST {{apiURL}}/toggleIsPostsPublic
Authorization: {{token}}

###ToggleIsLikesPublic test
POST {{apiURL}}/toggleIsLikesPublic
Authorization: {{token}}

###Get Profile test
GET {{apiURL}}/profileId/138904712213692416

###Get Profile test + token
GET {{apiURL}}/profileId/139146330835517440
Authorization: {{token}}

###Get Profile by username test
GET {{apiURL}}/profile/Gami

###Get Profile by username test + token
GET {{apiURL}}/profile/Gami2
Authorization: {{token}}



###TEST
POST {{apiURL}}/post
Authorization: {{token}}


###GET POSTS CHRONO
GET {{apiURL}}/postsChrono/0


###GET POSTS CHRONO + TOKEN
GET {{apiURL}}/postsChrono/0
Authorization: {{token}}


###togglePin
POST {{apiURL}}/togglePin
Authorization: {{token}}

{
	"postID":"139284701805281282"
}

###toggleLike
POST {{apiURL}}/toggleLike
Authorization: {{token}}

{
	"postID":"139284701805281282"
}

###toggleFollow
POST {{apiURL}}/toggleFollow
Authorization: {{token}}

{
	"profileID":"139146330835517440"
}


###getPins
GET {{apiURL}}/pins/0
Authorization: {{token}}


###getPost
GET {{apiURL}}/post/162430153014640642


###getPostReplies
GET {{apiURL}}/post-replies/162430153014640642/0

###getLoggedInUserProfile
GET {{apiURL}}/profile
Authorization: Hello Gami