@apiURL = http://localhost:8080

###REMEMBER TO NOT PUT TRAILING COMMAS IN JSON REQUESTS
GET {{apiURL}}/examples HTTP/2.0
# curl -X POST -H "Content-Type: application/json" --data "{\"username\":\"john\",\"password\":\"doe\", \"email\":\"email\"}" localhost:8080/register
###FAILED REGISTER
POST {{apiURL}}/register
Content-Type: "application/json"

{
	"username": "test",
	"password": "TestTest123",
	"email": "email"
}



###SUCCESSFUL REGISTER
POST {{apiURL}}/register
Content-Type: "application/json"

{
	"username": "Gami",
	"password": "Haslo123",
	"email": "gamiofficial0@gmail.com"
}

###FAILED LOGIN
POST {{apiURL}}/login
Content-Type: "application/json"

{
	"email": "test@test.com",
	"password": "TestTest13",
	"deviceName": "testDevice"
}

###SUCCESSFUL LOGIN
POST {{apiURL}}/login
Content-Type: "application/json"

{
	"email": "gamiofficial0@gmail.com",
	"password": "Haslo123",
	"deviceName": "testDevice"
}


###FAILED LOGOUT

POST {{apiURL}}/logout
Authorization: yesss


@token = 139448575558942761.rijpCM39qxNiacWHWejbfTcugtpNiuNLvihZPGyxx_3y95SwFq46qQX0O2AejOORZ9m-MT0e5DoQwKiVRRIrkxwCnwYoewdNlQTLH7vY9LNVv5E0_hw8ODmHp8GlBOo-fjLzz3c3jrKMvTKjWvYR9dWG7EMVFunHTCDMfTKqE5Y

###setDisplayName test
POST {{apiURL}}/setDisplayName
Authorization: {{token}}
Content-Type: "application/json"

{
	"displayName": "Gami The Creator"
}

###setBio test
POST {{apiURL}}/setBio
Authorization: {{token}}
Content-Type: "application/json"

{
	"bio": "Im just a silly little dude :3"
}

###ToggleIsFollowersPublic test
POST {{apiURL}}/toggleIsFollowersPublic
Authorization: {{token}}

###ToggleIsFollowingPublic test
POST {{apiURL}}/toggleIsFollowingPublic
Authorization: {{token}}

###ToggleIsPostsPublic test
POST {{apiURL}}/toggleIsPostsPublic
Authorization: {{token}}

###ToggleIsLikesPublic test
POST {{apiURL}}/toggleIsLikesPublic
Authorization: {{token}}

###Get Profile test
GET {{apiURL}}/profileId/138904712213692416

###Get Profile test + token
GET {{apiURL}}/profileId/138904712213692416
Authorization: {{token}}

###Get Profile by username test
GET {{apiURL}}/profile/Gami

###Get Profile by username test + token
GET {{apiURL}}/profile/Gami
Authorization: {{token}}



###TEST
POST {{apiURL}}/post
Authorization: {{token}}

###togglePin
POST {{apiURL}}/togglePin
Authorization: {{token}}

{
	"postID":"139349861414731794"
}